nodeLinker: node-modules

supportedArchitectures:
  cpu: [x64, arm64]
  os: [linux, win32, darwin]

packageExtensions:
  "@typescript-eslint/utils@*":
    peerDependencies:
      eslint: "*"
  "eslint-plugin-react@*":
    peerDependencies:
      eslint: "*"
  "eslint-plugin-react-refresh@*":
    peerDependencies:
      eslint: "*"
  "eslint-plugin-vitest@*":
    peerDependencies:
      eslint: "*"
