nodeLinker: node-modules

packageExtensions:
  "@typescript-eslint/utils@*":
    peerDependencies:
      eslint: "*"
  "eslint-plugin-react@*":
    peerDependencies:
      eslint: "*"
  "eslint-plugin-react-refresh@*":
    peerDependencies:
      eslint: "*"
  "eslint-plugin-vitest@*":
    peerDependencies:
      eslint: "*"
